### ISSUE TITLE
Replacement for strophe.jingle?

### ISSUE THREAD

**Issue by sualko** [otalk/jingle.js#25]
Hey guys,

I am looking for an alternative for [strophe.jingle](https://github.com/estos/strophe.jingle) and I am not sure if this library is able to replace it. What do you think?

**Comment by fippo** [comment]
it was originally planned to be a drop-in replacement. The session handling is definetly better

**Comment by sualko** [comment]
Thanks for your very quick response. 

Do you know if there occurs any conflicts with browserify and any other library? Is there any elegant solution to capsule the hole bundle?

Would you be interested in some documentation about the change?

**Comment by sualko** [comment]
Is your example outdated? I see

```
var jingle = new Jingle();
```

But I guess it should be

```
var jingle = new SessionManager();
```

**Comment by fippo** [comment]
no, you would require it like this.
```
var Jingle = require('jingle');
```
@legastero?

**Comment by sualko** [comment]
Ah ok, but this should be added to your example. It was confusing to me, because your class/function is called <code>SessionManager</code> in <code>index.js</code>.

**Comment by fippo** [comment]
probably a good idea.

Did you see https://github.com/otalk/stanza.io/blob/master/lib/plugins/jingle.js -- this shows the integration into stanza.io. You probably want to look at two things:
https://github.com/otalk/stanza.io/blob/master/lib/plugins/jingle.js#L41 to send things and
https://github.com/otalk/stanza.io/blob/master/lib/plugins/jingle.js#L54 to process incoming iq-set stanzas.
Not sure about the format that is expected, you probably need to json-ify things. Probably best to look at how the https://github.com/legastero/jingle-interop-demos process things. Or wait for Lance to chime in :-)

**Comment by sualko** [comment]
I saw the stanza.io integration and I think stanza.io looks very interesting in general.

Thanks for the jingle-interop-demos, because a working example is always a great help.

**Comment by sualko** [comment]
You should also add the incoming signalling channel to your example. Something like:

```
conn.on('iq:set:jingle', function (data) {
   jingle.process(data);
});
```

In general I have to say, that this library is not easy to understand for a developer without any stanza.io experience and someone, who wants to use an other signalling channel than stanza. I guess this comes in parts from the fact that there is no jsdoc or similar documentation.

**Comment by legastero** [comment]
Was [the API reference](https://github.com/otalk/jingle.js/blob/master/docs/Reference.md) helpful at all?

If you're integrating with Strophe, the data payloads that Jingle.js uses for audio/video come from https://github.com/otalk/sdp-jingle-json.

**Comment by fippo** [comment]
@legastero but sdp-jingle-json never deals with xml-ish jingle, right?

**Comment by legastero** [comment]
@fippo True, but neither does Jingle.js. We assume we are provided a JSON representation of requests, and we provide JSON responses because that provides a unified interface we can use with any JS library, even non-XMPP ones. Turning those objects into/from XML is left to the module providing the XMPP library integration.

**Comment by sualko** [comment]
The API reference was only particular helpful, because e.g. not all events are listed (peerStreamAdded, ringing, ...).

I think, I don't have to work with sdp-jingle-json directly, because it is used by RTCPeerConnection which is used by jingle-media-session, which is used by jingle.js (very confusing for a beginner). But I use jxt to transform json objects to xml and visa versa.

I try to create a strophe plugin, which works as an replacement for strophe.jingle, but currently I am struggling with the following error:

```
Failed to set remote offer sdp: RTCP-MUX must be enabled when BUNDLE is enabled.
```

Do you have accidentally any idea? I can no longer see the wood for the trees.

**Comment by fippo** [comment]
sounds like you're not mapping a=rtcp-mux -- can you show the xml input and sdp output?

**Comment by sualko** [comment]
How do I get the sdp output?

**Comment by sualko** [comment]
```
type: offer, sdp: v=0
o=- 1435008856481 1435008856487 IN IP4 0.0.0.0
s=-
t=0 0
a=group:BUNDLE audio video
m=audio 1 RTP/SAVPF 111 103
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:+S3GL/b0L/zpoba7
a=ice-pwd:dhUVIEQwS1Rn7XNUTS6rFpaX
a=fingerprint:sha-256 13:48:35:4A:04:3B:91:1A:23:C5:F0:53:18:3C:35:C9:3E:61:6A:36:DA:6C:B2:29:DA:E3:34:90:05:B1:BD:E7
a=setup:actpass
a=sendrecv
a=mid:audio
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10
a=rtpmap:103 ISAC/16000
m=video 1 RTP/SAVPF 100 116
c=IN IP4 0.0.0.0
a=rtcp:1 IN IP4 0.0.0.0
a=ice-ufrag:+S3GL/b0L/zpoba7
a=ice-pwd:dhUVIEQwS1Rn7XNUTS6rFpaX
a=fingerprint:sha-256 13:48:35:4A:04:3B:91:1A:23:C5:F0:53:18:3C:35:C9:3E:61:6A:36:DA:6C:B2:29:DA:E3:34:90:05:B1:BD:E7
a=setup:actpass
a=sendrecv
a=mid:video
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtpmap:116 red/90000
```

**Comment by fippo** [comment]
you're (at least) not mapping the <rtcp-mux/> which should be a child of the <description/>
-- possibly some other things like xep-0339 <source/> elements.

**Comment by sualko** [comment]
I guess my XML-JSON mapping is not working correctly, because it says e.g. <code>jingle.contents[0].description.mux: false</code>. I will investigate this tomorrow. Thanks for your help.

**Comment by sualko** [comment]
I could fix my problem and I will close this issue after I released my strophe plugin. Is that ok for you?

**Comment by sualko** [comment]
https://github.com/sualko/strophe.jinglejs

It is not completely finished, but it is working (most of the time). Thanks for your great help.
