### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by sualko** [otalk/jingle.js#31]
Do you have a changelog somewhere? I think this would be super helpfull for upgrades.

Is there any reason, why you do not create new tags for new builds?

**Comment by xdumaine** [comment]
There aren't rapid changes on this project, so [the commit log](https://github.com/otalk/jingle.js/commits/master) is a pretty good change log.

**Comment by sualko** [comment]
But the commit log is full of commits which do not affect the library itself. e.g. documentation, tests, typos, ... 

Anyway, I can also live without a changelog file. Thank you for your quick response.
