### ISSUE TITLE
Results aren't processed.

### ISSUE THREAD

**Issue by xdumaine** [otalk/jingle.js#34]
Results are sent ([source](https://github.com/otalk/jingle.js/blob/master/index.js#L396)):

``` javascript
    session.process(action, req.jingle, function (err) {
        if (err) {
            ......
        } else {
            self.emit('send', {
                to: sender,
                id: rid,
                type: 'result',
            });
            ......
        }
    });
```

But when processed ([source](https://github.com/otalk/jingle.js/blob/master/index.js#L263)): 

``` javascript
    var self = this;

    // Extract the request metadata that we need to verify
    var sid = !!req.jingle ? req.jingle.sid : null;
    var session = this.sessions[sid] || null;
    var rid = req.id;
    var sender = req.from.full || req.from;

    if (req.type === 'error') {
        ......
    }

    if (req.type === 'result') {
        if (session) {
            session.pendingAction = false;
        }
        return;
    }
```

`sid` is not included in results, so the `session` is never found, and `pendingAction` is never cleared.

**Comment by xdumaine** [comment]
@fippo @legastero looks like results don't take a `<jingle/>` node inside them - thoughts on how to fix this one?

**Comment by legastero** [comment]
Is this actually causing problematic behaviour, or are you just wanting to clean up the state?

The whole `pendingAction` thing is incorrect and needs to be changed entirely.

**Comment by xdumaine** [comment]
It's causing problematic behavior - it fails to process a stream change after having *made* a stream change.

**Comment by xdumaine** [comment]
I.e., use switchStream on client A, then switchStream on client B - client A will fail to process the change.

**Comment by xdumaine** [comment]
A workaround adding the jingle sid to the data before processing from a separate cache makes this work fine, but should not be required. If it requires the Sid to be transmitted, JingleJs should include it.
