### ISSUE TITLE
any updated demo ?

### ISSUE THREAD

**Issue by moeinrahimi** [otalk/jingle.js#47]
is there any demo that really works ? i have ejabberd xmpp server and i'm trying to run a demo video chat and there is no demo that works

**Comment by moeinrahimi** [comment]
i'm trying to run this demo 
https://github.com/legastero/jingle-interop-demos/tree/gh-pages/stanzaio
and i get this error after trying to make call
``` javascript
stanzaio.bundle.js:24600 Uncaught TypeError: Cannot read property 'id' of undefined
    at dumpStream (stanzaio.bundle.js:24600)
    at TraceablePeerConnection.addStream (stanzaio.bundle.js:24709)
    at MediaSession.addStream (stanzaio.bundle.js:25802)
    at HTMLFormElement.callInfo.onsubmit (index.html:125)
```
which refers to this 
``` javascript
function dumpStream(stream) {
    var info = {
        label: stream.id,
    };
```

**Comment by fippo** [comment]
those demos are -- as you noticed -- quite outdated, not using the latest versions of the libraries etc.

**Comment by moeinrahimi** [comment]
so i update all dependencies used in demo and now i get 
``` javascript
Argument 1 of RTCPeeConnection.addStream is not a function
```

**Comment by moeinrahimi** [comment]
i managed to go further and make the video call , 
this is my code using stanza.io and jingle.js
i can see data logs in other client that i'm trying to call but the voice won't connect
i guess because of this line       session.addStream(localMedia.localStream);
localMedia.localStream is undefined


``` javascript
var localMedia = require('localMedia');
var localMedia = new localMedia()
localMedia.on('localStream', function (stream) {
  console.log('localstream')
    attachMediaStream(stream, document.getElementById('localVideo'), {
        mirror: true,
        muted: true
    });
  });
  client.on('jingle:remotestream:added', function (session, stream) {
    console.log(stream,'ssss')
    var video = document.querySelector('#remoteVideo');
    video.srcObject = stream;
});
client.on('jingle:incoming', function (session) {
  
    if (session.addStream) {
      console.log('injaaaaaaa',session,localMedia.localStream)
      session.addStream(localMedia.localStream);
    }
    session.accept();
});
client.connect();
var callInfo = document.getElementById('callInfo');
callInfo.onsubmit = function (e) {
  e.preventDefault();
  var jid = document.getElementById('peer').value;
  navigator.getUserMedia({ video: true },
    function(stream) {
      var sess = client.jingle.createMediaSession(jid);
      sess.addStream(stream);
      sess.start();
       var video = document.querySelector('#localVideo');
       video.srcObject = stream;

    },
    function(err) {
       console.log("The following error occurred: " + err.name);
    }
 );

};
```

**Comment by fippo** [comment]
well, you are trying to circumvent the localmedia module by calling getUsermedia yourself. Mixing this up will not work, either don't use localMedia or use it the way it is intended

**Comment by moeinrahimi** [comment]
yes i know what's your point , but using localMedia i will get errors that i belive it's related to library itself , would you guide me on how i can get the video from jingle

**Comment by xdumaine** [comment]
@moeinrahimi You should be able to use localMedia and jingle.js (and jingle-media-session) without hacking around issues. Are you including adapter.js (`webrtc/webrtc-adapter` project on github, `webrtc-adapter` on npm)? That should resolve the `addStream` error you posted.
